extends:
  - airbnb
  - airbnb/hooks
rules:
  no-restricted-syntax: off
  no-param-reassign:
    - error
    - props: false
  jsx-a11y/label-has-associated-control: off
  react/forbid-prop-types: off
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .js
        - .jsx
  react/function-component-definition:
    - 1
    - 
      namedComponents: 
        - function-declaration
        - function-expression
        - arrow-function
      unnamedComponents:
        - function-expression
        - arrow-function
parserOptions:
  ecmaVersion: 2020
env:
  browser: true




